runtime: php73 # Replace with php74 to use PHP 7.4

runtime_config:
  document_root: .


handlers:

 #Serve images as static resources.
- url: /(.+\.(gif|png|jpg|css|js|PNG|map))$
  static_files: \1
  upload: .+\.(gif|png|jpg|css|js|PNG|map)$

# Serve your app through a front controller at index.php or public/index.php.
- url: .*
  script: auto